export const TODO_LS_KEY = 'todos'
export const TITLE_DESCRIPTION = 'Get things done, one item at a time.'
export const ARTHUR = 'Enzo Luo'
export const ARTHUR_GITHUB = 'https://github.com/CoolizzLuo'
export const ARTHUR_MAIL = 'coolizz1010@gmail.com'
export const COPYRIGHT_YEAR = '2021'